//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int ID { get; set; }
        public string ImageLinks { get; set; }
        public string Texts { get; set; }
        public string SoundLinks { get; set; }
        public int OptionOne { get; set; }
        public int OptionTwo { get; set; }
        public string OptionOneText { get; set; }
        public string OptionTwoText { get; set; }
    }
}
