//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectLink
    {
        public int ID { get; set; }
        public string Sounds { get; set; }
        public string Pictures { get; set; }
        public string Paragraphs { get; set; }
        public string OptionOneText { get; set; }
        public int OptionOneID { get; set; }
        public string OptionTwoText { get; set; }
        public int OptionTwoID { get; set; }
    }
}
